#!/bin/sh
# Verification harness for the mod generator. See verification/README.md.
#
# Usage: verification/verify.sh [options]
#   --byte              require byte-identical output vs the baseline
#   --canonical         (default) allow order/formatting differences that the
#                       canonicalisation rules declare non-semantic
#   --world             compare the PATCHED game documents instead of the diffs
#                       (allows representation changes, e.g. replace vs remove+add)
#   --baseline <ref>    git ref to build the baseline from (default: HEAD)
#   --skip-sim          skip the patch simulation / schema / summary layers
#   --with-tests        also run the F# logic test battery (dotnet test)
#   --update-golden     rewrite verification/world_summary.golden from this run
#
# The baseline is generated by building and running the generator at the given
# git ref in a temporary worktree (output is deterministic, so "what <ref>
# produces" is always well defined). Cached per commit in verification/cache/.
set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJ=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$PROJ"

TIER="canonical"
REF="HEAD"
SIM=1
TESTS=0
UPDATE_GOLDEN=0
while [ $# -gt 0 ]; do
    case "$1" in
        --byte) TIER="byte" ;;
        --canonical) TIER="canonical" ;;
        --world) TIER="world" ;;
        --baseline) REF="$2"; shift ;;
        --skip-sim) SIM=0 ;;
        --with-tests) TESTS=1 ;;
        --update-golden) UPDATE_GOLDEN=1 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

MOD_OUT="$PROJ/mod/after_the_fall"
FAILED=0

echo "== build & run (working tree) =="
dotnet build 2>&1 | grep -E "error|warning|Build succeeded|Build FAILED" || true
dotnet run > "$SCRIPT_DIR/last_run.log" 2>&1 || {
    echo "RUN FAILED - tail of verification/last_run.log:"
    tail -20 "$SCRIPT_DIR/last_run.log"
    exit 1
}

SHA=$(git rev-parse "$REF")
CACHE="$SCRIPT_DIR/cache/$SHA/after_the_fall"
if [ ! -d "$CACHE" ]; then
    echo "== generating baseline from $REF ($SHA) =="
    WT=$(mktemp -d /tmp/x4verify.XXXXXX)
    rmdir "$WT"
    git worktree add --detach "$WT" "$SHA" > /dev/null
    ln -s "$PROJ/X4_unpacked_data" "$WT/X4_unpacked_data"
    if ! (cd "$WT" && dotnet run > run.log 2>&1); then
        echo "BASELINE BUILD FAILED - tail of its run.log:"
        tail -20 "$WT/run.log"
        git worktree remove --force "$WT"
        exit 1
    fi
    mkdir -p "$(dirname "$CACHE")"
    cp -R "$WT/mod/after_the_fall" "$CACHE"
    git worktree remove --force "$WT"
fi

echo "== compare vs $REF (tier: $TIER) =="
if [ "$TIER" = "world" ]; then
    WORLDS=$(mktemp -d /tmp/x4world.XXXXXX)
    python3 "$SCRIPT_DIR/simulate.py" --mod "$CACHE" --dump "$WORLDS/baseline" --quiet > /dev/null || true
    python3 "$SCRIPT_DIR/simulate.py" --mod "$MOD_OUT" --dump "$WORLDS/current" --quiet > /dev/null || true
    python3 "$SCRIPT_DIR/compare_canonical.py" "$WORLDS/baseline" "$WORLDS/current" \
        --require canonical --rules world --quiet || FAILED=1
    rm -rf "$WORLDS"
else
    python3 "$SCRIPT_DIR/compare_canonical.py" "$CACHE" "$MOD_OUT" --require "$TIER" --quiet || FAILED=1
fi

if [ "$SIM" = 1 ]; then
    echo "== patch simulation, selector audit, schemas =="
    python3 "$SCRIPT_DIR/simulate.py" --mod "$MOD_OUT" --quiet || FAILED=1

    echo "== world summary vs golden =="
    SUMMARY=$(mktemp /tmp/x4summary.XXXXXX)
    python3 "$SCRIPT_DIR/world_summary.py" "$MOD_OUT" > "$SUMMARY"
    if [ "$UPDATE_GOLDEN" = 1 ]; then
        cp "$SUMMARY" "$SCRIPT_DIR/world_summary.golden"
        echo "world_summary.golden updated"
    elif [ -f "$SCRIPT_DIR/world_summary.golden" ]; then
        if diff -u "$SCRIPT_DIR/world_summary.golden" "$SUMMARY"; then
            echo "world summary matches golden"
        else
            echo "WORLD SUMMARY CHANGED (intentional? rerun with --update-golden)"
            FAILED=1
        fi
    else
        echo "no world_summary.golden yet - run with --update-golden to create it"
    fi
    rm -f "$SUMMARY"
fi

if [ "$TESTS" = 1 ]; then
    echo "== F# logic tests =="
    (cd "$PROJ/X4MLParser.Tests" && dotnet test 2>&1 | tail -2) || FAILED=1
fi

echo
if [ "$FAILED" = 0 ]; then
    echo "VERIFY PASSED (tier: $TIER, baseline: $REF)"
else
    echo "VERIFY FAILED"
    exit 1
fi
